name : Looking at MLB Draft through WAR - Baseball Hack Day 2015 project
brand : <i class="fa fa-bar-chart"></i>
description : Project for 2015 Baseball Hack Day by Daigo Fujiwara, Chad Curll, and David Thrysson
keyword : 
url : http://daigofuji.github.io/jekyll-foundation-5-starter/
email : daigo@daigofujiwara.com
twitter : DaigoFuji
github : DaigoFuji
author : Daigo Fujiwara
analytics : UA-8418273-8
year : 2015
markdown : kramdown
